package com.physics91.korma.gradle

import org.gradle.api.Action
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import java.io.File
import javax.inject.Inject

/**
 * Gradle extension for configuring Korma code generation.
 *
 * Usage in build.gradle.kts:
 * ```kotlin
 * korma {
 *     packageName.set("com.example.db.tables")
 *     outputDirectory.set(file("src/main/kotlin"))
 *
 *     database {
 *         url.set("jdbc:postgresql://localhost:5432/mydb")
 *         username.set("user")
 *         password.set("pass")
 *     }
 *
 *     codegen {
 *         generateEntities.set(true)
 *         generateKdoc.set(true)
 *         include("users", "orders")
 *         exclude(".*_backup")
 *     }
 * }
 * ```
 */
abstract class KormaExtension @Inject constructor(objects: ObjectFactory) {

    /**
     * Package name for generated classes.
     */
    val packageName: Property<String> = objects.property(String::class.java)
        .convention("com.example.db.generated")

    /**
     * Output directory for generated files.
     */
    val outputDirectory: Property<File> = objects.property(File::class.java)

    /**
     * Database configuration.
     */
    val database: DatabaseExtension = objects.newInstance(DatabaseExtension::class.java)

    /**
     * Code generation options.
     */
    val codegen: CodegenExtension = objects.newInstance(CodegenExtension::class.java)

    /**
     * Configure database settings.
     */
    fun database(action: Action<DatabaseExtension>) {
        action.execute(database)
    }

    /**
     * Configure code generation options.
     */
    fun codegen(action: Action<CodegenExtension>) {
        action.execute(codegen)
    }
}

/**
 * Database connection configuration.
 */
abstract class DatabaseExtension @Inject constructor(objects: ObjectFactory) {

    /**
     * JDBC URL for the database connection.
     */
    val url: Property<String> = objects.property(String::class.java)

    /**
     * Database username.
     */
    val username: Property<String> = objects.property(String::class.java)

    /**
     * Database password.
     */
    val password: Property<String> = objects.property(String::class.java)

    /**
     * JDBC driver class name.
     */
    val driverClassName: Property<String> = objects.property(String::class.java)

    /**
     * Database schema to introspect.
     */
    val schema: Property<String> = objects.property(String::class.java)

    /**
     * Configure PostgreSQL connection.
     */
    fun postgresql(host: String, port: Int = 5432, database: String) {
        url.set("jdbc:postgresql://$host:$port/$database")
        driverClassName.set("org.postgresql.Driver")
    }

    /**
     * Configure MySQL connection.
     */
    fun mysql(host: String, port: Int = 3306, database: String) {
        url.set("jdbc:mysql://$host:$port/$database")
        driverClassName.set("com.mysql.cj.jdbc.Driver")
    }

    /**
     * Configure H2 in-memory connection.
     */
    fun h2(database: String) {
        url.set("jdbc:h2:mem:$database")
        driverClassName.set("org.h2.Driver")
    }

    /**
     * Configure SQLite connection.
     */
    fun sqlite(path: String) {
        url.set("jdbc:sqlite:$path")
        driverClassName.set("org.sqlite.JDBC")
    }
}

/**
 * Code generation options.
 */
abstract class CodegenExtension @Inject constructor(objects: ObjectFactory) {

    /**
     * Whether to generate entity data classes.
     */
    val generateEntities: Property<Boolean> = objects.property(Boolean::class.java)
        .convention(true)

    /**
     * Whether to generate KDoc comments.
     */
    val generateKdoc: Property<Boolean> = objects.property(Boolean::class.java)
        .convention(true)

    /**
     * Whether to use nullable types for nullable columns.
     */
    val useNullableTypes: Property<Boolean> = objects.property(Boolean::class.java)
        .convention(true)

    /**
     * File header comment for generated files.
     */
    val fileHeader: Property<String> = objects.property(String::class.java)
        .convention("Generated by Korma Codegen. Do not edit manually.")

    /**
     * Table name patterns to include (regex).
     */
    val includePatterns: ListProperty<String> = objects.listProperty(String::class.java)
        .convention(listOf(".*"))

    /**
     * Table name patterns to exclude (regex).
     */
    val excludePatterns: ListProperty<String> = objects.listProperty(String::class.java)
        .convention(emptyList())

    /**
     * Add table name patterns to include.
     */
    fun include(vararg patterns: String) {
        includePatterns.set(patterns.toList())
    }

    /**
     * Add table name patterns to exclude.
     */
    fun exclude(vararg patterns: String) {
        excludePatterns.set(patterns.toList())
    }
}
