codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_not_found: success
        only_pulls: false
    patch:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  branches:
    - main
    - develop

flags:
  unittests:
    paths:
      - "korma-core/"
      - "korma-jdbc/"
      - "korma-r2dbc/"
      - "korma-dao/"
      - "korma-cache/"
      - "korma-migration/"
    carryforward: true

ignore:
  - "**/*Test.kt"
  - "**/test/**"
  - "**/build/**"
  - "korma-benchmark/**"
