package com.physics91.korma.codegen.config

import java.nio.file.Path
import java.nio.file.Paths

/**
 * Configuration for code generation.
 *
 * Usage:
 * ```kotlin
 * val config = CodegenConfig(
 *     packageName = "com.example.db.tables",
 *     outputDirectory = Paths.get("src/main/kotlin"),
 *     databaseConfig = DatabaseConfig(
 *         url = "jdbc:postgresql://localhost:5432/mydb",
 *         username = "user",
 *         password = "pass"
 *     )
 * )
 * ```
 */
data class CodegenConfig(
    /**
     * Package name for generated classes.
     */
    val packageName: String,

    /**
     * Output directory for generated files.
     */
    val outputDirectory: Path = Paths.get("src/main/kotlin"),

    /**
     * Database connection configuration.
     */
    val databaseConfig: DatabaseConfig,

    /**
     * Naming strategy for generated classes and properties.
     */
    val namingStrategy: NamingStrategy = NamingStrategy.Default,

    /**
     * Whether to generate entity classes in addition to table objects.
     */
    val generateEntities: Boolean = true,

    /**
     * Whether to generate DAO interfaces.
     */
    val generateDaos: Boolean = false,

    /**
     * Schema to introspect (null for default schema).
     */
    val schema: String? = null,

    /**
     * Table name patterns to include (regex).
     */
    val includePatterns: List<Regex> = listOf(Regex(".*")),

    /**
     * Table name patterns to exclude (regex).
     */
    val excludePatterns: List<Regex> = emptyList(),

    /**
     * Whether to add KDoc comments to generated code.
     */
    val generateKdoc: Boolean = true,

    /**
     * Whether to use nullable types for nullable columns.
     */
    val useNullableTypes: Boolean = true,

    /**
     * File header comment.
     */
    val fileHeader: String? = "Generated by Korma Codegen. Do not edit manually.",

    /**
     * Type mappings for custom column types.
     */
    val customTypeMappings: Map<String, TypeMapping> = emptyMap()
) {
    /**
     * Builder for CodegenConfig.
     */
    class Builder {
        var packageName: String = "com.example.db.generated"
        var outputDirectory: Path = Paths.get("src/main/kotlin")
        var databaseConfig: DatabaseConfig? = null
        var namingStrategy: NamingStrategy = NamingStrategy.Default
        var generateEntities: Boolean = true
        var generateDaos: Boolean = false
        var schema: String? = null
        var includePatterns: List<Regex> = listOf(Regex(".*"))
        var excludePatterns: List<Regex> = emptyList()
        var generateKdoc: Boolean = true
        var useNullableTypes: Boolean = true
        var fileHeader: String? = "Generated by Korma Codegen. Do not edit manually."
        private val customTypeMappings = mutableMapOf<String, TypeMapping>()

        fun packageName(name: String) = apply { this.packageName = name }
        fun outputDirectory(path: Path) = apply { this.outputDirectory = path }
        fun outputDirectory(path: String) = apply { this.outputDirectory = Paths.get(path) }
        fun database(config: DatabaseConfig) = apply { this.databaseConfig = config }
        fun database(block: DatabaseConfig.Builder.() -> Unit) = apply {
            this.databaseConfig = DatabaseConfig.Builder().apply(block).build()
        }
        fun namingStrategy(strategy: NamingStrategy) = apply { this.namingStrategy = strategy }
        fun generateEntities(value: Boolean) = apply { this.generateEntities = value }
        fun generateDaos(value: Boolean) = apply { this.generateDaos = value }
        fun schema(name: String?) = apply { this.schema = name }
        fun include(vararg patterns: String) = apply {
            this.includePatterns = patterns.map { Regex(it) }
        }
        fun exclude(vararg patterns: String) = apply {
            this.excludePatterns = patterns.map { Regex(it) }
        }
        fun generateKdoc(value: Boolean) = apply { this.generateKdoc = value }
        fun useNullableTypes(value: Boolean) = apply { this.useNullableTypes = value }
        fun fileHeader(header: String?) = apply { this.fileHeader = header }
        fun mapType(sqlType: String, kotlinType: TypeMapping) = apply {
            this.customTypeMappings[sqlType.uppercase()] = kotlinType
        }

        fun build(): CodegenConfig {
            return CodegenConfig(
                packageName = packageName,
                outputDirectory = outputDirectory,
                databaseConfig = databaseConfig
                    ?: throw IllegalStateException("Database configuration is required"),
                namingStrategy = namingStrategy,
                generateEntities = generateEntities,
                generateDaos = generateDaos,
                schema = schema,
                includePatterns = includePatterns,
                excludePatterns = excludePatterns,
                generateKdoc = generateKdoc,
                useNullableTypes = useNullableTypes,
                fileHeader = fileHeader,
                customTypeMappings = customTypeMappings.toMap()
            )
        }
    }

    companion object {
        fun builder() = Builder()
    }
}

/**
 * Database connection configuration.
 */
data class DatabaseConfig(
    val url: String,
    val username: String? = null,
    val password: String? = null,
    val driverClassName: String? = null
) {
    class Builder {
        var url: String = ""
        var username: String? = null
        var password: String? = null
        var driverClassName: String? = null

        fun url(url: String) = apply { this.url = url }
        fun username(username: String?) = apply { this.username = username }
        fun password(password: String?) = apply { this.password = password }
        fun driver(className: String?) = apply { this.driverClassName = className }

        // Convenience methods for common databases
        fun h2(database: String) = apply {
            this.url = "jdbc:h2:mem:$database"
            this.driverClassName = "org.h2.Driver"
        }

        fun postgresql(host: String, port: Int = 5432, database: String) = apply {
            this.url = "jdbc:postgresql://$host:$port/$database"
            this.driverClassName = "org.postgresql.Driver"
        }

        fun mysql(host: String, port: Int = 3306, database: String) = apply {
            this.url = "jdbc:mysql://$host:$port/$database"
            this.driverClassName = "com.mysql.cj.jdbc.Driver"
        }

        fun sqlite(path: String) = apply {
            this.url = "jdbc:sqlite:$path"
            this.driverClassName = "org.sqlite.JDBC"
        }

        fun build() = DatabaseConfig(url, username, password, driverClassName)
    }

    companion object {
        fun builder() = Builder()
    }
}

/**
 * Custom type mapping for code generation.
 */
data class TypeMapping(
    /**
     * Fully qualified Kotlin type name.
     */
    val kotlinType: String,

    /**
     * Import statements needed for this type.
     */
    val imports: List<String> = emptyList(),

    /**
     * Korma column type function to use (e.g., "varchar", "integer").
     */
    val columnTypeFunction: String? = null
)

/**
 * DSL function to create CodegenConfig.
 */
fun codegenConfig(block: CodegenConfig.Builder.() -> Unit): CodegenConfig {
    return CodegenConfig.Builder().apply(block).build()
}
